---
#                                          _              _  __      _       __     ___            _        
#  _ __ ___   ___ _ __ ___   ___ __ _  ___| |__   ___  __| |/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ ` _ \ / _ \ '_ ` _ \ / __/ _` |/ __| '_ \ / _ \/ _` | || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | | | | |  __/ | | | | | (_| (_| | (__| | | |  __/ (_| | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_| |_| |_|\___|_| |_| |_|\___\__,_|\___|_| |_|\___|\__,_| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                                           \_\_|        |___/_/                            
# install-pkg
- block:
    - name: install-pkg | Amazon | memcached{{ memcached.version }} repository should be enabled
      when: ansible_distribution == "Amazon"
      shell: >
        amazon-linux-extras list
        |  grep memcached{{ memcached.version }}
        |  grep enabled 
        || amazon-linux-extras enable memcached{{ memcached.version}}
      changed_when: false

    - name: install-pkg | RedHat | memcached should be installed
      yum:
        name:  "memcached"
        state: "present"
  when: ansible_os_family == "RedHat"

