---
#                                          _              _  __      _       __     ___            _        
#  _ __ ___   ___ _ __ ___   ___ __ _  ___| |__   ___  __| |/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ ` _ \ / _ \ '_ ` _ \ / __/ _` |/ __| '_ \ / _ \/ _` | || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | | | | |  __/ | | | | | (_| (_| | (__| | | |  __/ (_| | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_| |_| |_|\___|_| |_| |_|\___\__,_|\___|_| |_|\___|\__,_| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                                           \_\_|        |___/_/                            
# tasks file for ar-memcached-pkg
- include: install-pkg.yml
- include: make-config.yml
- include: build-local.yml
- include: boot-script.yml

